Launcher3: Bump min SDK to 26 as required for adaptive icons
Addresses the following compilation error:

  packages/apps/Launcher/res/mipmap-anydpi/ic_pixeldust_launcher.xml: error: <adaptive-icon> elements require a sdk version of at least 26.

Change-Id: I5684e917ef0b691d99e2e59fd742d7570dfd1007
Signed-off-by: spezi77 <spezi7713@gmx.net>